#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点配置
title: "你好世界"
description: "Just So So ..."
keywords: "分享生活,分享技术"

# 用户信息配置
username: 用户名称
github: https://github.com
email: root@admin.com

# Markdown配置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil

# 地址配置
baseurl: "/"
url: "https://zgcwkj.github.io"

# 分页配置
paginate: 10
paginate_path: "page/:num"

# scss配置
sass:
  sass_dir: /assets/pithy/css
  style: :compressed

# 评论系统配置 https://github.com/imsun/gitment
githubowner: zgcwkj
githubrepo: zgcwkj.github.io
clientid: b0951a87d9540a49b727
clientsecret: e55b7782f85149dacb1b4a6a0dd692f7e049e901
